# 3.2 Parts of Speech (POS) Tagging

In [2]:
%pip install spacy

Collecting spacy
  Downloading spacy-3.8.16-cp313-cp313-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp313-cp313-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp313-cp313-win_amd64.whl.metadata (5.4 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp313-cp313-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp313-cp313-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Downloading weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Using cached confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (0.20.0)
Requirement already satisfied: click<9.0.0,>=8.2.1 in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (8.4.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (2.3.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (2.12.4)
Requirement already satisfied: jinja2 in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\anaconda3\lib\site-packages (from spacy) (25.0)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\lib\site-packages (from click<9.0.0,>=8.2.1->spacy) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Downloading blis-1.3.3-cp313-cp313-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\lenovo\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading cloudpathlib-0.25.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open>=5.2.1 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading smart_open-8.0.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: httpx>=0.24.0 in c:\users\lenovo\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.10.0)
Requirement already satisfied: httpcore==1.* in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\lenovo\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenovo\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in c:\users\lenovo\anaconda3\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\lenovo\anaconda3\lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jinja2->spacy) (3.0.2)
Downloading spacy-3.8.16-cp313-cp313-win_amd64.whl (15.2 MB)
   ---------------------------------------- 0.0/15.2 MB ? eta -:--:--
   ----- ---------------------------------- 2.1/15.2 MB 11.1 MB/s eta 0:00:02
   ----------- ---------------------------- 4.5/15.2 MB 10.9 MB/s eta 0:00:01
   ----------------- ---------------------- 6.8/15.2 MB 10.9 MB/s eta 0:00:01
   ------------------------ --------------- 9.2/15.2 MB 10.9 MB/s eta 0:00:01
   ----------------------------- ---------- 11.3/15.2 MB 10.8 MB/s eta 0:00:01
   ----------------------------------- ---- 13.6/15.2 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------  14.9/15.2 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------- 15.2/15.2 MB 9.9 MB/s  0:00:01
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading confection-1.3.3-py3-none-any.whl (35 kB)
Downloading cymem-2.0.13-cp313-cp313-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp313-cp313-win_amd64.whl (25 kB)
Downloading preshed-3.0.13-cp313-cp313-win_amd64.whl (122 kB)
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp313-cp313-win_amd64.whl (650 kB)
   ---------------------------------------- 0.0/650.8 kB ? eta -:--:--
   ---------------------------------------- 650.8/650.8 kB 7.2 MB/s  0:00:00
Downloading thinc-8.3.13-cp313-cp313-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 10.2 MB/s  0:00:00
Downloading blis-1.3.3-cp313-cp313-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ------------- -------------------------- 2.1/6.2 MB 10.0 MB/s eta 0:00:01
   --------------------------- ------------ 4.2/6.2 MB 10.1 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 9.7 MB/s  0:00:00
Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-1.0.0-py3-none-any.whl (50 kB)
Downloading cloudpathlib-0.25.0-py3-none-any.whl (66 kB)
Downloading smart_open-8.0.1-py3-none-any.whl (73 kB)
Installing collected packages: wasabi, spacy-loggers, spacy-legacy, smart-open, murmurhash, cymem, confection, cloudpathlib, catalogue, blis, srsly, preshed, thinc, weasel, spacy

   -- -------------------------------------  1/15 [spacy-loggers]
   ----- ----------------------------------  2/15 [spacy-legacy]
   -------- -------------------------------  3/15 [smart-open]
   ------------- --------------------------  5/15 [cymem]
   ------------------ ---------------------  7/15 [cloudpathlib]
   ------------------ ---------------------  7/15 [cloudpathlib]
   --------------------- ------------------  8/15 [catalogue]
   ------------------------ ---------------  9/15 [blis]
   -------------------------- ------------- 10/15 [srsly]
   -------------------------- ------------- 10/15 [srsly]
   -------------------------- ------------- 10/15 [srsly]
   -------------------------- ------------- 10/15 [srsly]
   -------------------------- ------------- 10/15 [srsly]
   -------------------------- ------------- 10/15 [srsly]
   -------------------------- ------------- 10/15 [srsly]
   -------------------------- ------------- 10/15 [srsly]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   -------------------------------- ------- 12/15 [thinc]
   ---------------------------------- ----- 13/15 [weasel]
   ---------------------------------- ----- 13/15 [weasel]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ------------------------------------- -- 14/15 [spacy]
   ---------------------------------------- 15/15 [spacy]

Successfully installed blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.25.0 confection-1.3.3 cymem-2.0.13 murmurhash-1.0.15 preshed-3.0.13 smart-open-8.0.1 spacy-3.8.16 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.3 thinc-8.3.13 wasabi-1.1.3 weasel-1.0.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
import spacy
import pandas as pd

In [8]:
nlp = spacy.load('en_core_web_sm')
# if you are running this for the first time, or recieve an error "Can't find model 'en_core_web_sm'", 
# then please run the follwing in your terminal: python -m spacy download en_core_web_sm

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

In [3]:
# our text is from jane austin's 'emma'
# we have removed punctuation, lowercased but left in stop words
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [4]:
# create a spacy doc from our text - this will generate tokens and their assosciated pos tags
spacy_doc = nlp(emma_ja)

In [5]:
# extract the tokens and pos tags into a dataframe
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])

In [6]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df,
                       pd.DataFrame.from_records([{'token': token.text, 'pos_tag': token.pos_}])], ignore_index=True)

In [7]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [8]:
# token frequency count
pos_df_counts = pos_df.groupby(['token','pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)
pos_df_counts.head(10)

    token pos_tag  counts
88     of     ADP      14
49    had     AUX       9
54    her    PRON       9
111   the     DET       8
6     and   CCONJ       8
0       a     DET       6
114    to    PART       5
61     in     ADP       4
13   been     AUX       4
120  very     ADV       4

In [9]:
# counts of pos_tags
pos_df_poscounts = pos_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)
pos_df_poscounts.head(10)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
Name: token, dtype: int64

In [10]:
# see most common nouns
nouns = pos_df_counts[pos_df_counts.pos_tag == "NOUN"][0:10]
nouns

         token pos_tag  counts
48   governess    NOUN       3
46      friend    NOUN       3
130      years    NOUN       2
35        emma    NOUN       2
28   daughters    NOUN       2
103    sisters    NOUN       2
82      mother    NOUN       2
89      office    NOUN       1
78    mistress    NOUN       1
75    mildness    NOUN       1

In [11]:
# see most common verbs
verbs = pos_df_counts[pos_df_counts.pos_tag == "ADJ"][0:10]
verbs

           token pos_tag  counts
70        little     ADJ       2
91           own     ADJ       1
86       nominal     ADJ       1
79          more     ADJ       1
102        short     ADJ       1
98          rich     ADJ       1
34         early     ADJ       1
26   comfortable     ADJ       1
25        clever     ADJ       1
16          best     ADJ       1